export const DEFAULT_PERMISSIONS: {
  code: string;
  name: string;
  group: string;
  isCustom?: boolean;
}[] = [
  { code: 'apiAdminCompanyCompanyIdAiLogRead', isCustom: false, name: 'Admin Company AI Log: Read', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdAppsRead', isCustom: false, name: 'Api Admin Company Company Id Apps Read', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdCompanyMemberCompanyMemberIdDelete', isCustom: false, name: 'Api Admin Company Company Id Company Member Company Member Id Delete', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdCompanyMemberCompanyMemberIdRead', isCustom: false, name: 'Api Admin Company Company Id Company Member Company Member Id Read', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdCompanyMemberCompanyMemberIdUpdate', isCustom: false, name: 'Api Admin Company Company Id Company Member Company Member Id Update', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdCompanyMemberCreate', isCustom: false, name: 'Api Admin Company Company Id Company Member Create', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdCompanyMemberRead', isCustom: false, name: 'Api Admin Company Company Id Company Member Read', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdFeatureCodesFeatureCodeCreate', isCustom: false, name: 'Api Admin Company Company Id Feature Codes Feature Code Create', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdFeatureCodesFeatureCodeDelete', isCustom: false, name: 'Api Admin Company Company Id Feature Codes Feature Code Delete', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdFeatureCodesRead', isCustom: false, name: 'Api Admin Company Company Id Feature Codes Read', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdFeatureCodesUpdate', isCustom: false, name: 'Api Admin Company Company Id Feature Codes Update', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdRead', isCustom: false, name: 'Api Admin Company Company Id Read', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdRoleRoleNameResetCreate', isCustom: false, name: 'Api Admin Company Company Id Role Role Name Reset Create', group: '_admin' },
  { code: 'apiAdminCompanyCompanyIdUpdate', isCustom: false, name: 'Api Admin Company Company Id Update', group: '_admin' },
  { code: 'apiAdminCompanyCreate', isCustom: false, name: 'Api Admin Company Create', group: '_admin' },
  { code: 'apiAdminCompanyRead', isCustom: false, name: 'Api Admin Company Read', group: '_admin' },
  { code: 'apiAdminFeatureFeatureIdDelete', isCustom: false, name: 'Api Admin Feature Feature Id Delete', group: '_admin' },
  { code: 'apiAdminFeatureFeatureIdRead', isCustom: false, name: 'Api Admin Feature Feature Id Read', group: '_admin' },
  { code: 'apiAdminFeatureFeatureIdUpdate', isCustom: false, name: 'Api Admin Feature Feature Id Update', group: '_admin' },
  { code: 'apiAdminFeatureRead', isCustom: false, name: 'Api Admin Feature Read', group: '_admin' },
  { code: 'apiAdminOpenapiSpecRead', isCustom: false, name: 'Api Admin Openapi Spec Read', group: '_admin' },
  { code: 'apiAdminPermissionCreate', isCustom: false, name: 'Api Admin Permission Create', group: '_admin' },
  { code: 'apiAdminPermissionGroupRenameCreate', isCustom: false, name: 'Api Admin Permission Group Rename Create', group: '_admin' },
  { code: 'apiAdminPermissionPermissionIdDelete', isCustom: false, name: 'Api Admin Permission Permission Id Delete', group: '_admin' },
  { code: 'apiAdminPermissionPermissionIdRead', isCustom: false, name: 'Api Admin Permission Permission Id Read', group: '_admin' },
  { code: 'apiAdminPermissionPermissionIdUpdate', isCustom: false, name: 'Api Admin Permission Permission Id Update', group: '_admin' },
  { code: 'apiAdminPermissionRead', isCustom: false, name: 'Api Admin Permission Read', group: '_admin' },
  { code: 'apiAdminUsersRead', isCustom: false, name: 'Api Admin Users Read', group: '_admin' },
  { code: 'apiAdminUsersUserIdRead', isCustom: false, name: 'Api Admin Users User Id Read', group: '_admin' },
  { code: 'apiAdminUsersUserIdSessionsDelete', isCustom: false, name: 'Api Admin Users User Id Sessions Delete', group: '_admin' },
  { code: 'apiAdminUsersUserIdSessionsRead', isCustom: false, name: 'Api Admin Users User Id Sessions Read', group: '_admin' },
  { code: 'apiAdminWeaveAppsAppIdDelete', isCustom: false, name: 'Api Admin Weave Apps App Id Delete', group: '_admin' },
  { code: 'apiAdminWeaveAppsAppIdPublishToCompanyCompanyIdCreate', isCustom: false, name: 'Api Admin Weave Apps App Id Publish To Company Company Id Create', group: '_admin' },
  { code: 'apiAdminWeaveAppsAppIdPublishToCompanyCompanyIdDelete', isCustom: false, name: 'Api Admin Weave Apps App Id Publish To Company Company Id Delete', group: '_admin' },
  { code: 'apiAdminWeaveAppsAppIdRead', isCustom: false, name: 'Api Admin Weave Apps App Id Read', group: '_admin' },
  { code: 'apiAdminWeaveAppsAppIdUpdate', isCustom: false, name: 'Api Admin Weave Apps App Id Update', group: '_admin' },
  { code: 'apiAdminWeaveAppsCreate', isCustom: false, name: 'Api Admin Weave Apps Create', group: '_admin' },
  { code: 'apiAdminWeaveAppsRead', isCustom: false, name: 'Api Admin Weave Apps Read', group: '_admin' },
  { code: 'apiAppBuilderCompileCreate', isCustom: false, name: 'Api App Builder Compile Create', group: 'app-builder' },
  { code: 'apiAppsCompanyIdAppIdDelete', isCustom: false, name: 'Api Apps Company Id App Id Delete', group: 'app-manage' },
  { code: 'apiAppsCompanyIdAppIdRead', isCustom: false, name: 'Api Apps Company Id App Id Read', group: 'user-basics' },
  { code: 'apiAppsCompanyIdAppIdUpdate', isCustom: false, name: 'Api Apps Company Id App Id Update', group: 'app-manage' },
  { code: 'apiAppsCompanyIdCreate', isCustom: false, name: 'Api Apps Company Id Create', group: 'app-manage' },
  { code: 'apiAppsCompanyIdRead', isCustom: false, name: 'Api Apps Company Id Read', group: 'user-basics' },
  { code: 'apiAppStatsCompanyIdCreate', isCustom: false, name: 'Api App Stats Company Id Create', group: 'user-basics' },
  { code: 'apiAppStatsCompanyIdExportRead', isCustom: false, name: 'Api App Stats Company Id Export Read', group: 'app-manage' },
  { code: 'apiAppStatsCompanyIdRead', isCustom: false, name: 'Api App Stats Company Id Read', group: 'app-manage' },
  { code: 'apiBrowserExtensionCompanyIdSettingsRead', isCustom: false, name: 'Api Browser Extension Company Id Settings Read', group: 'user-basics' },
  { code: 'apiCompanyCompanyIdAiLogRead', isCustom: false, name: 'Api Company Company Id Ai Log Read', group: 'company-ai-logs-view' },
  { code: 'apiCompanyCompanyIdFeErrorsCreate', isCustom: false, name: 'Api Company Company Id Fe Errors Create', group: 'user-basics' },
  { code: 'apiCompanyCompanyIdRead', isCustom: false, name: 'Api Company Company Id Read', group: 'user-basics' },
  { code: 'apiCompanyCompanyIdRolesRoleNamePermissionsRead', isCustom: false, name: 'Api Company Company Id Roles Role Name Permissions Read', group: 'user-basics' },
  { code: 'apiCompanyCompanyIdRolesRoleNamePermissionsUpdate', isCustom: false, name: 'Api Company Company Id Roles Role Name Permissions Update', group: 'company-roles-permissions-manage' },
  { code: 'apiCompanyCompanyIdUpdate', isCustom: false, name: 'Api Company Company Id Update', group: 'company-details-manage' },
  { code: 'apiCompanyCompanyIdUserAutocompleteRead', isCustom: false, name: 'Api Company Company Id User Autocomplete Read', group: 'user-basics' },
  { code: 'apiCompanyCompanyIdUserDisplayNameCreate', isCustom: false, name: 'Api Company Company Id User Display Name Create', group: 'company-enterprise-console-general' },
  { code: 'apiCompanyMemberCompanyIdCompanyMemberIdDelete', isCustom: false, name: 'Api Company Member Company Id Company Member Id Delete', group: 'company-members-manage' },
  { code: 'apiCompanyMemberCompanyIdCompanyMemberIdRead', isCustom: false, name: 'Api Company Member Company Id Company Member Id Read', group: 'user-basics' },
  { code: 'apiCompanyMemberCompanyIdCompanyMemberIdUpdate', isCustom: false, name: 'Api Company Member Company Id Company Member Id Update', group: 'company-members-manage' },
  { code: 'apiCompanyMemberCompanyIdCreate', isCustom: false, name: 'Api Company Member Company Id Create', group: 'company-members-manage' },
  { code: 'apiCompanyMemberCompanyIdRead', isCustom: false, name: 'Api Company Member Company Id Read', group: 'user-basics' },
  { code: 'apiCompanyRead', isCustom: false, name: 'Api Company Read', group: 'user-basics' },
  { code: 'apiDataApiTargetTypeTargetIdAiCompanyIdCreate', isCustom: false, name: 'Api Data Api Target Type Target Id Ai Company Id Create', group: 'data-api' },
  { code: 'apiDataApiTargetTypeTargetIdCompanyIdCompanyMembersRead', isCustom: false, name: 'Api Data Api Target Type Target Id Company Id Company Members Read', group: 'data-api' },
  { code: 'apiDataApiTargetTypeTargetIdCompanyIdCreate', isCustom: false, name: 'Api Data Api Target Type Target Id Company Id Create', group: 'data-api' },
  { code: 'apiDataApiTargetTypeTargetIdCompanyIdDataIdDelete', isCustom: false, name: 'Api Data Api Target Type Target Id Company Id Data Id Delete', group: 'data-api' },
  { code: 'apiDataApiTargetTypeTargetIdCompanyIdDataIdRead', isCustom: false, name: 'Api Data Api Target Type Target Id Company Id Data Id Read', group: 'data-api' },
  { code: 'apiDataApiTargetTypeTargetIdCompanyIdDataIdUpdate', isCustom: false, name: 'Api Data Api Target Type Target Id Company Id Data Id Update', group: 'data-api' },
  { code: 'apiDataApiTargetTypeTargetIdCompanyIdRead', isCustom: false, name: 'Api Data Api Target Type Target Id Company Id Read', group: 'data-api' },
  { code: 'apiEmailsCompanyIdRead', isCustom: false, name: 'Api Emails Company Id Read', group: 'company-emails-manage' },
  { code: 'apiEmailsCompanyIdTemplateCategoryNameDelete', isCustom: false, name: 'Api Emails Company Id Template Category Name Delete', group: 'company-emails-manage' },
  { code: 'apiEmailsCompanyIdTemplateCategoryNameRead', isCustom: false, name: 'Api Emails Company Id Template Category Name Read', group: 'company-emails-manage' },
  { code: 'apiEmailsCompanyIdTemplateCategoryNameUpdate', isCustom: false, name: 'Api Emails Company Id Template Category Name Update', group: 'company-emails-manage' },
  { code: 'apiFormCompanyIdCreate', isCustom: false, name: 'Api Form Company Id Create', group: 'forms-manage' },
  { code: 'apiFormCompanyIdFormIdDelete', isCustom: false, name: 'Api Form Company Id Form Id Delete', group: 'forms-manage' },
  { code: 'apiFormCompanyIdFormIdRead', isCustom: false, name: 'Api Form Company Id Form Id Read', group: 'forms-view' },
  { code: 'apiFormCompanyIdFormIdUpdate', isCustom: false, name: 'Api Form Company Id Form Id Update', group: 'forms-manage' },
  { code: 'apiFormCompanyIdRead', isCustom: false, name: 'Api Form Company Id Read', group: 'forms-view' },
  { code: 'apiLocationsCompanyIdCreate', isCustom: false, name: 'Api Locations Company Id Create', group: 'locations-manage' },
  { code: 'apiLocationsCompanyIdLocationIdDelete', isCustom: false, name: 'Api Locations Company Id Location Id Delete', group: 'locations-manage' },
  { code: 'apiLocationsCompanyIdLocationIdDescendantsRead', isCustom: false, name: 'Api Locations Company Id Location Id Descendants Read', group: 'user-basics' },
  { code: 'apiLocationsCompanyIdLocationIdRead', isCustom: false, name: 'Api Locations Company Id Location Id Read', group: 'user-basics' },
  { code: 'apiLocationsCompanyIdLocationIdUpdate', isCustom: false, name: 'Api Locations Company Id Location Id Update', group: 'locations-manage' },
  { code: 'apiLocationsCompanyIdRead', isCustom: false, name: 'Api Locations Company Id Read', group: 'user-basics' },
  { code: 'apiPermissionsRead', isCustom: false, name: 'Api Permissions Read', group: 'user-basics' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdAccessRulesCreate', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Access Rules Create', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdAccessRulesRead', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Access Rules Read', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdAccessRulesRuleIdDelete', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Access Rules Rule Id Delete', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdAccessRulesRuleIdRead', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Access Rules Rule Id Read', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdAccessRulesRuleIdUpdate', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Access Rules Rule Id Update', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdDataRulesCreate', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Data Rules Create', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdDataRulesDataRuleIdDelete', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Data Rules Data Rule Id Delete', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdDataRulesDataRuleIdRead', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Data Rules Data Rule Id Read', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdDataRulesDataRuleIdUpdate', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Data Rules Data Rule Id Update', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdDataRulesRead', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Data Rules Read', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdWebhooksCreate', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Webhooks Create', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdWebhooksRead', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Webhooks Read', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdWebhooksWebhookIdDelete', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Webhooks Webhook Id Delete', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdWebhooksWebhookIdLogsLogIdReplayCreate', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Webhooks Webhook Id Logs Log Id Replay Create', group: 'workflows-triggers-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdWebhooksWebhookIdLogsRead', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Webhooks Webhook Id Logs Read', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdWebhooksWebhookIdRead', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Webhooks Webhook Id Read', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeTargetIdWebhooksWebhookIdUpdate', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Target Id Webhooks Webhook Id Update', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeWebhooksSharedCreate', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Webhooks Shared Create', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeWebhooksSharedRead', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Webhooks Shared Read', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeWebhooksSharedWebhookIdDelete', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Webhooks Shared Webhook Id Delete', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeWebhooksSharedWebhookIdLogsRead', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Webhooks Shared Webhook Id Logs Read', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeWebhooksSharedWebhookIdRead', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Webhooks Shared Webhook Id Read', group: 'rules-and-webhooks-manage' },
  { code: 'apiRulesAndHooksCompanyIdTargetTypeWebhooksSharedWebhookIdUpdate', isCustom: false, name: 'Api Rules And Hooks Company Id Target Type Webhooks Shared Webhook Id Update', group: 'user-basics' },
  { code: 'apiStartupUrlGroupCompanyIdCreate', isCustom: false, name: 'Api Startup Url Group Company Id Create', group: 'company-browser-extension-manage' },
  { code: 'apiStartupUrlGroupCompanyIdGroupIdDelete', isCustom: false, name: 'Api Startup Url Group Company Id Group Id Delete', group: 'company-browser-extension-manage' },
  { code: 'apiStartupUrlGroupCompanyIdGroupIdRead', isCustom: false, name: 'Api Startup Url Group Company Id Group Id Read', group: 'user-basics' },
  { code: 'apiStartupUrlGroupCompanyIdGroupIdUpdate', isCustom: false, name: 'Api Startup Url Group Company Id Group Id Update', group: 'company-browser-extension-manage' },
  { code: 'apiStartupUrlGroupCompanyIdMyUrlsRead', isCustom: false, name: 'Api Startup Url Group Company Id My Urls Read', group: 'user-basics' },
  { code: 'apiStartupUrlGroupCompanyIdRead', isCustom: false, name: 'Api Startup Url Group Company Id Read', group: 'user-basics' },
  { code: 'apiUserCurrentRead', isCustom: false, name: 'Api User Current Read', group: 'user-basics' },
  { code: 'apiUserCurrentUpdate', isCustom: false, name: 'Api User Current Update', group: 'user-basics' },
  { code: 'apiWorkflowsTriggersTriggerCompanyIdCreate', isCustom: false, name: 'Api Workflows Triggers Trigger Company Id Create', group: 'workflows-triggers-manage' },
  { code: 'apiWorkflowsTriggersTriggerCompanyIdRead', isCustom: false, name: 'Api Workflows Triggers Trigger Company Id Read', group: 'workflows-triggers-use' },
  { code: 'apiWorkflowsTriggersTriggerCompanyIdTriggerIdDelete', isCustom: false, name: 'Api Workflows Triggers Trigger Company Id Trigger Id Delete', group: 'workflows-triggers-manage' },
  { code: 'apiWorkflowsTriggersTriggerCompanyIdTriggerIdRead', isCustom: false, name: 'Api Workflows Triggers Trigger Company Id Trigger Id Read', group: 'workflows-triggers-use' },
  { code: 'apiWorkflowsTriggersTriggerCompanyIdTriggerIdStatCreate', isCustom: false, name: 'Api Workflows Triggers Trigger Company Id Trigger Id Stat Create', group: 'workflows-triggers-use' },
  { code: 'apiWorkflowsTriggersTriggerCompanyIdTriggerIdStatRead', isCustom: false, name: 'Api Workflows Triggers Trigger Company Id Trigger Id Stat Read', group: 'workflows-triggers-use' },
  { code: 'apiWorkflowsTriggersTriggerCompanyIdTriggerIdUpdate', isCustom: false, name: 'Api Workflows Triggers Trigger Company Id Trigger Id Update', group: 'workflows-triggers-manage' },
  { code: 'apiWorkflowsTriggersWorkflowCompanyIdCreate', isCustom: false, name: 'Api Workflows Triggers Workflow Company Id Create', group: 'workflows-triggers-manage' },
  { code: 'apiWorkflowsTriggersWorkflowCompanyIdRead', isCustom: false, name: 'Api Workflows Triggers Workflow Company Id Read', group: 'workflows-triggers-use' },
  { code: 'apiWorkflowsTriggersWorkflowCompanyIdWorkflowIdDelete', isCustom: false, name: 'Api Workflows Triggers Workflow Company Id Workflow Id Delete', group: 'workflows-triggers-manage' },
  { code: 'apiWorkflowsTriggersWorkflowCompanyIdWorkflowIdRead', isCustom: false, name: 'Api Workflows Triggers Workflow Company Id Workflow Id Read', group: 'workflows-triggers-use' },
  { code: 'apiWorkflowsTriggersWorkflowCompanyIdWorkflowIdStatCreate', isCustom: false, name: 'Api Workflows Triggers Workflow Company Id Workflow Id Stat Create', group: 'workflows-triggers-use' },
  { code: 'apiWorkflowsTriggersWorkflowCompanyIdWorkflowIdStatRead', isCustom: false, name: 'Api Workflows Triggers Workflow Company Id Workflow Id Stat Read', group: 'workflows-triggers-use' },
  { code: 'apiWorkflowsTriggersWorkflowCompanyIdWorkflowIdUpdate', isCustom: false, name: 'Api Workflows Triggers Workflow Company Id Workflow Id Update', group: 'workflows-triggers-manage' },
  { code: 'feEnterpriseAppLoad', isCustom: true, name: 'Enterprise App Load', group: 'company-enterprise-console-general' },
];
